canonifyURLs = true
languageCode = "en-us"
theme = "hugo-docs"

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "vs"
tabWidth = 4

[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

# set by build script: title, baseurl
title = "Dgraph Documentation"

[params]
discourse = "https://discuss.dgraph.io/"
site = "dgraph-docs"
[security]
  enableInlineShortcodes = true
  [security.funcs]
    getenv = ['^HUGO_', '^CI$','VERSIONS','CURRENT_VERSION','CANONICAL_PATH','CURRENT_BRANCH','DGRAPH_ENDPOINT','CURRENT_LATEST_TAG']
